version: '3.8'  

services:  
  app:  
    build: .  
    volumes:  
      - ./src:/app/src  # Для горячей перезагрузки  
    environment:  
      DB_USER: postgres  
      DB_PASSWORD: postgres  
      DB_HOST: db  # Имя сервиса PostgreSQL  
      DB_PORT: 5432  
      DB_NAME: my_library  
    ports:  
      - "80:80"  

  db:  
    image: postgres:13  
    environment:  
      POSTGRES_USER: postgres  
      POSTGRES_PASSWORD: postgres  
      POSTGRES_DB: my_library  
    ports:  
      - "5432:5432"  # Отступ скорректирован  

  nginx:  
    image: nginx:alpine  # Используем легкий образ Nginx  
    ports:  
      - "80:80"  
    volumes:  
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf  # Копируем конфигурацию Nginx  
    depends_on:  
      - app  