services:
  app:
    build: .
    volumes:
      - ./src:/app/src
    environment:
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: my_library_3
      SECRET_KEY: secret_key
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 30
      EMAIL_HOST: smtp.yandex.ru
      EMAIL_PORT: 465
      EMAIL_HOST_USER: gefest-173@yandex.ru
      EMAIL_HOST_PASSWORD: lppxxgxpqpdqabzw
      EMAIL_USE_SSL: 'True'  # Обратите внимание, что это строка
      CELERY_BROKER_URL: 'amqp://guest:guest@rabbitmq//'
    ports:
      - "8000:80"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: my_library_3
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"  # Для подключения к RabbitMQ
      - "15672:15672"  # Для доступа к веб-интерфейсу RabbitMQ

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app